env: dev
application:
  name: adbackendadapter
  javaoptions: -Xms256m -Xmx512m
replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/fuse-uat-pipelines/adbackendadapter
  pullPolicy: Always
  tag: "v7"
service:
  type: ClusterIP
  port: 9903
route:
  enabled: true
  host: adbackendadapter.apps.tclnprdservices.tatacapital.com
  path: /
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 80
labels:
  component: adbackendadapter
  deploymentconfig: adbackendadapter
  group: tatacapital
  project: adbackendadapter
  provider: s2i
  version: 1.0.0
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 50m
    memory: 256Mi
readinessProbe:
  httpGet:
    scheme: HTTP
    path: /rest/adbackend/v1.0/healthCheckReadiness
    port: 9903
  periodSeconds: 25
  initialDelaySeconds: 40
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  httpGet:
    scheme: HTTP
    path: /rest/adbackend/v1.0/healthCheckLiveness
    port: 9903
  timeoutSeconds: 1
  periodSeconds: 30
  initialDelaySeconds: 60
  successThreshold: 1
  failureThreshold: 3
nodeSelector: {}
tolerations: []
affinity: {}
