apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmrepo-fuseapp.fullname" . }}
  labels:
    {{- include "helmrepo-fuseapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmrepo-fuseapp.selectorLabels" . | nindent 4 }}
